# Generated by Django 4.1.2 on 2022-11-10 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='1998-03-24'),
            preserve_default=False,
        ),
    ]
